"""added spreadsheet url for user model

Revision ID: 02385e7fe322
Revises: f8a7b6c5d4e3
Create Date: 2026-03-31 10:25:09.694424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02385e7fe322'
down_revision: Union[str, None] = 'f8a7b6c5d4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spreadsheet_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spreadsheet_url')
    # ### end Alembic commands ###
