"""added rent and buy urls

Revision ID: 578f70af6c57
Revises: 02385e7fe322
Create Date: 2026-03-31 10:32:08.870130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578f70af6c57'
down_revision: Union[str, None] = '02385e7fe322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spreadsheet_rent_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('spreadsheet_buy_url', sa.String(), nullable=True))
    op.drop_column('users', 'spreadsheet_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spreadsheet_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'spreadsheet_buy_url')
    op.drop_column('users', 'spreadsheet_rent_url')
    # ### end Alembic commands ###
