"""added channel_name field to channel_messages table

Revision ID: 7e256e8086b7
Revises: a5184a6649d3
Create Date: 2026-04-20 13:32:06.092927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e256e8086b7"
down_revision: Union[str, None] = "a5184a6649d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_messages", sa.Column("channel_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_messages", "channel_name")
    # ### end Alembic commands ###
