"""added installment_plan

Revision ID: bc69457aed79
Revises: 7e256e8086b7
Create Date: 2026-06-28 00:11:53.979793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc69457aed79'
down_revision: Union[str, None] = '7e256e8086b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('installment_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'installment_plan')
    # ### end Alembic commands ###
